### ISSUE TITLE
Poloniex price data

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/core#1]
User Story Link: https://trello.com/c/Lx4iyOey/30-poloniex

# Description and Context

We use Poloniex pricing data on all coins tradable with BTC. The goal here is to put individual price data points in a low-latency database for later running analytics.

This data is the root source for every trade signal our services produces for trading crypto on Poloniex. If this process goes down, the entire service will go down so failover will also need to be in place.

# Possible Implementation

## Input

reference issue #5 where Poloniex data is collected and saved in this format
```
{
'channel': 'Poloniex',
'type': 'exchange'
'data': json_data,
'timestamp': int(timestamp_unix_seconds)
}
```

Then input for this is the json_data

## Process

This data should process and save before or during the datastore logic in issue #5. It is absolutely critical that this price data is usable as soon as possible.

From the json_data above, get each coin pair that is tradable with BTC and extract its price. Convert the price to satoshis. Assuming the price is less than 1 BTC, the value in satoshis will always be an integer less than 100000000 or 10^8

## Output

For Each coin (BTC_XXX):
Save this data in BigTable

- coin symbol (eg. OMG)
- coin price (eg. 273423)
- timestamp (same as input above)

If any data does not exist or is malformed, do not save anything for that coin.

be sure to always following standard formats described in issue #7 

# Environment

- Worker on App Engine
- Google Cloud BigTable

**Comment by firemanxbr** [comment]
I have a question about our data format, for example:

Data from **Poloniex**
"USDT_BTC": {
                         "id": 121,
                         "last": "4299.83910206",
                         "lowestAsk": "4303.36090490",
                         "highestBid": "4299.83910173",
                         "percentChange": "0.02193889",
                         "baseVolume": "13544812.40817353",
                         "quoteVolume": "3205.52764611",
                         "isFrozen": "0",
                         "high24hr": "4339.50000000",
                         "low24hr": "4131.00000007"
}

Data inserted into **BigTable**
{
    "data": {
       ...
        "USDT": {
                       "USDT_BTC_CHANGE": "-0.03732411",
                       "USDT_BTC_HIGH": "4368.58692255",
                       "USDT_BTC_LAST": "4349.50000036",
                       "USDT_BTC_LOW": "4131.00000007",
                       "USDT_BTC_VOLUME": "13883173.35101755",
        },
    "row_key": "poloniex#1507236084"
}

**Question 1**
How to convert all data ? we have *_CHANGE sometimes as negative value. The others fields are float don't supported to Satoshi units. PS: If we convert float to integer we lost some indicators, for example: "4349.91293198"  

tests:
$ python3
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> (1 / float("4349.50000036")) * 10 ** 8
**22991.148405960037**

>>> (1 / int("4349.50000036")) * 10 ** 8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ValueError: invalid literal for int() with base 10: '4349.50000036'**

If we look the other values not about the USD, for example:
"ETH": {
            "ETH_BCH_CHANGE": "-0.02400539",
            "ETH_BCH_HIGH": "1.25918666",
            "ETH_BCH_LAST": "1.19616922",
            "ETH_BCH_LOW": "1.18808616",
            "ETH_BCH_VOLUME": "1006.47608056",
},

**Question 2**
This is a perfect example of convert float to integer will lost relevant percentage. for example:

$ python3
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> (1.19616922) * 10 ** 8
119616922.0

>>> int(1.19616922) * 10 ** 8
100000000

**Comment by firemanxbr** [comment]
Solved on Telegram. Definitions:

Convert to Satoshi:
int(float("1.19616922") * 10 ** 8)

Fields required: 
"*_LAST": 119616922
"*_VOLUME": 100647608056

**Comment by firemanxbr** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2614

**Comment by firemanxbr** [comment]
We have a problem about the origin values(Poloniex) to BigTable as satoshis.
We get the values in this API:

https://poloniex.com/public?command=returnTicker   

If we check some values like this:

"baseVolume": "832.97385735"
"last": "4742.38619994"

How works the convertions:

baseVolume: int(float("832.97385735") * 10 ** 8)
>> 83297385735 (11 units)

last: int(float("4742.38619994") * 10 ** 8)
>> 474238619993 (12 units)

BigTable support only big endian integers with 4-bytes like this example by Google:
https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/python/thrift/flask_thrift.py 

Try convertions like this:
struct.pack(">i", 83297385735)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

If we try increment to 8-bytes like this:
struct.pack(">q", 83297385735)
'\x00\x00\x00\x13d\xe9=\x07'

BigTable don't accept:
Error: (False, ValueError("invalid literal for int() with base 10: ''",))

In that case we have a alternative to save all values as string to calculate using Python or JavaScript or BigQuery is easier and don't have any benefits to this conversions before and after save this values because BigTable don't have functions to calculate internally.
